### PR TITLE
Add easyocr 1.6.2

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/JaidedAI/EasyOCR/blob/v1.6.2/releasenotes.md
License: https://github.com/JaidedAI/EasyOCR/blob/v1.6.2/LICENSE
Requirements:
- https://github.com/JaidedAI/EasyOCR/blob/v1.6.2/requirements.txt
- https://github.com/JaidedAI/EasyOCR/blob/v1.6.2/setup.py

Actions:
1. Add `readme` to the recipe 
2. Add `vs2019` for `win` to `conda_build_config.yaml`
3. Add `--no-deps` to `script`
4. Skip `s390x` and `ppc64le` (`torchvision` isn't available on those platforms)
5. Skip `py<37`
6. Fix `py-opencv` pinning as `>=4.6.0` to prevent using incompatible versions
7. Add `run_test.bat`, `run_test.sh`, and `run_test.py`
8. Add an example file for tests [recipe/english.png](https://github.com/AnacondaRecipes/easyocr-feedstock/pull/1/files#diff-5169731b29b98c5e9965c68e594f6980d3877f3aebc2e1b2fa2f95c50e0d5b57)
9. Skip lints:  `missing_pip_check`, `has_run_test_and_commands`, `build_tools_must_be_in_build`

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Waiting for openblas 0.3.21 https://github.com/AnacondaRecipes/openblas-feedstock/pull/15 and scipy v1.9.1 https://github.com/AnacondaRecipes/scipy-feedstock/pull/19

**Comment by skupr-anaconda** [comment]
openblas 0.3.21 and scipy v1.9.1 are available but we need to rebuild torchvision 0.11.3  to enable python 3.10 support https://github.com/AnacondaRecipes/torchvision-feedstock/pull/5

**Comment by skupr-anaconda** [comment]
torchvision 0.11.3  has been rebuilt

**Comment by skupr-anaconda** [comment]
I've rebuilt `torchvision 0.11.3` without `sysroot_linux-64 ==2.17` but another incompatibility issue of opencv/py-opencv still persists

**Review by katietz — APPROVED** [review]
thanks

**Review by ELundby45 — APPROVED** [review]

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
